<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="container boxTop p-5 d-flex flex-row mt-4 mb-5">
    <div class="row">
        <div class="col addMarginhome">
            <fieldset class="border border-dark px-5 w-100">
                <legend class="text-center">New</legend>
            <div class="textBox">
               <p>SPRING / SUMMER </br> COLLECTION</p>
               <div class="line" aria-hidden="false"></div>
            </div>
            </fieldset>
            <form class="signUp">
                <p class="mt-3 textFavorite">Our favorite collection</p>
                <button class="btn btn-outline-light btn-light w-50 mt-1" type="button">SHOP NOW</button>
            </form>
        </div>
    </div>
    <div class="col imgTop">
        <img class="p-4" src="<?= $this->basePath('img/imgTop-home.jpg') ?>" alt="Home page illustration image">
    </div>
</div>
<div class="mb-5">
    <div class="row">
        <div class="col titleTwo mt-5 text-center">
            <h1>Crafted with care</h1>
        </div>
    </div>
    <div class="row d-flex justify-content-evenly mt-3 boxTwo">
        <div class="col">
            <div class="card-group d-flex justify-content-between buttonCards">
                <div class="card border-0 rounded-0">
                    <img src="<?= $this->basePath('img/creme-graphic7.jpg') ?>" class="card-img-top" alt="...">
                    <button class="btn btn-outline-light btn-light w-50 mx-auto border-0 rounded-0" type="button">SHOP CANDLES</button>
                </div>
                <div class="card mx-4 border-0">
                    <img src="<?= $this->basePath('img/creme-graphic8.jpg') ?>" class="card-img-top" alt="...">
                    <button class="btn btn-outline-light btn-light w-50 mx-auto border-0 rounded-0" type="button">SHOP SETS</button>
                </div>
                <div class="card border-0 rounded-0">
                    <img src="<?= $this->basePath('img/creme-graphic9.jpeg') ?>" class="card-img-top" alt="...">
                    <button class="btn btn-outline-light btn-light w-50 mx-auto border-0 rounded-0" type="button">SHOP EXTRAS</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container boxCenter p-5 d-flex flex-row mt-4 mb-5">
    <div class="col imgTop">
        <img class="p-4" src="<?= $this->basePath('img/candle1.jpg') ?>" alt="Home page illustration image">
    </div>
    <div class="row">
        <div class="col addMarginhome text-white">
            <fieldset class="border border-light px-5 w-100">
                <legend class="text-center">Team</legend>
            <div class="textBox">
               <p>WE'RE JACOB *</br> MADISON</p>
               <div class="line-white" aria-hidden="false"></div>
            </div>
            </fieldset>
            <form class="signUp">
                <button class="btn btn-outline-light btn-light w-75 mt-4" type="button">READ OUR STORY</button>
            </form>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col titleTwo mt-5 text-center">
            <h1>From the blog</h1>
        </div>
        <div class="row mt-3">
            <div class="col">
                <div class="card-group cardEnd d-flex justify-content-between h-100 p-5">
                    <div class="card border-0 mr-5 bg-transparent">
                        <img src="<?= $this->basePath('img/spring-projects.jpg') ?>" class="card-img-top rounded-0" alt="...">
                        <div class="card-body">
                            <h5 class="card-title titleCard">OUR FAVORITE SPRING DIY PROJECTS</h5>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores voluptatum nihil neque magni eveniet distinctio expedita voluptatibus debitis dolorem saepe libero non, consequuntur aut tempore accusamus exercitationem dolores perferendis dicta?</p>
                        </div>
                    </div>
                    <div class="card border-0 bg-transparent">
                        <img src="<?= $this->basePath('img/gift-ideas.jpg') ?>" class="card-img-top rounded-0" alt="...">
                        <div class="card-body">
                            <h5 class="card-title titleCard">GIFT IDEAS FOR SOMEONE SPECIAL</h5>
                            <p class="card-text">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fuga ipsam labore corrupti sapiente. Repellat doloremque, asperiores saepe laboriosam adipisci sequi minima maxime, qui veniam labore ratione accusamus numquam voluptas quidem.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="w-100">
    <div class="bgAboveFooter" aria-hidden="false"></div>
</div>
<div class="container">
    <div class="row buttonVisit">
        <div class="col signUp d-flex justify-content-center my-5 d-block">
            <button class="btn btn-outline-light btn-light w-25 mt-1" type="button">VISIT THE BLOG</button>
        </div>
    </div>
</div>
